name: Blade Release

on:
  workflow_dispatch:
  push:
    branches: [adding-workflows]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Create Release Pull Request & Publish packages
        id: changesets
        uses: changesets/action@v1
        if: github.event_name != 'workflow_dispatch' # only run on master merges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: yarn release
          commit: 'build(test-monorepo): update version'
          title: 'build(test-monorepo): update version'
      - name: Publish to public npm registry
        if: steps.changesets.outputs.published == 'true' || github.event_name == 'workflow_dispatch' # run when the package is published via changeset or if a release is triggered manually.
        run: yarn publish-npm

          
